# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67908053994b96ffd8d77ecc9b4699b4cf932ad014c50ce6f3e21d55c234e7cfb08349b27874e1daec7028deabc03ed0c6134f05cf436190ffe2530d702b2bf7

test:
  secret_key_base: 66a18b212b733549a215770ca9f716196706a68747092cd442636f133bd036ba520eeae17af08bef1f5179695d818f1fe1e3adb9d35f77ea886ce29509b6b94f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
